export const images = {
  icons: {
    eyeClose: require('./assets/images/icons/eye-close.png'),
    home: require('./assets/images/icons/home.png'),
    plan: require('./assets/images/icons/plans.png'),
    arrowLeft: require('./assets/images/icons/back.png'),
    wallet: require('./assets/images/icons/wallet.png'),
    transfer: require('./assets/images/icons/transfer.png'),
    withdrawal: require('./assets/images/icons/withdrawal.png'),
    deposit: require('./assets/images/icons/deposit.png'),
    failedDeposit: require('./assets/images/icons/failedDeposit.png'),
    transferPlan: require('./assets/images/icons/transferPlan.png'),
    pending: require('./assets/images/icons/bankTransfer.png'),
    arrow: require('./assets/images/icons/arrow.png'),
    close: require('./assets/images/icons/close.png'),
    calender: require('./assets/images/icons/calender.png'),
    question: require('./assets/images/icons/question-mark.png'),
    settings: require('./assets/images/icons/settings.png'),
    bar: require('./assets/images/icons/bar.png'),
    arrow2: require('./assets/images/icons/arrow2.png'),
    rightArrow: require('./assets/images/icons/rightarrow.png'),
    creditCard: require('./assets/images/icons/credit-card.png'),
    image: require('./assets/images/icons/image.png'),
  },
  plans: {
    plan1: require('./assets/images/plans/plan2.png'),
    plan2: require('./assets/images/plans/plan3.png'),
  },
  illustrations: {
    realEstate: require('./assets/images/illustrations/real-estate.png'),
    radioOn: require('./assets/images/illustrations/radioActive.png'),
    radioOff: require('./assets/images/illustrations/radioInActive.png'),
  },
};
